# -*- coding: utf-8 -*-
"""mergedata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rtrMgOlGbfGvgtqMOge1nU1Q8EQtASF
"""

import os
import glob
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/ipn/AeroTTeam/data/Archives/'

all_filenames = ['039','040','054','055','056','057']
typ = 'train'
network = 'mlp'
recurrencia = 10
combined_input       = pd.concat([pd.read_csv(root_path + 'input_' + f + '_'+ typ +'_'+network+'_r{}.csv'.format(recurrencia), header=None ) for f in all_filenames ])
combined_output_rpm  = pd.concat([pd.read_csv(root_path + 'output_' + f + '_'+ typ +'_rpm_'+network+'_r{}.csv'.format(recurrencia), header=None ) for f in all_filenames ])
combined_output_pow  = pd.concat([pd.read_csv(root_path + 'output_' + f + '_'+ typ +'_pow_'+network+'_r{}.csv'.format(recurrencia), header=None ) for f in all_filenames ])
combined_output_torq = pd.concat([pd.read_csv(root_path + 'output_' + f + '_'+ typ +'_torq_'+network+'_r{}.csv'.format(recurrencia), header=None ) for f in all_filenames ])

print( "Inputs:\t{}".format(combined_input.shape) )
print( "Outputs rpm:\t{}".format(combined_output_rpm.shape) )
print( "Outputs pow:\t{}".format(combined_output_pow.shape) )
print( "Outputs torq:\t{}".format(combined_output_torq.shape) )

combined_input.to_csv( root_path+"input_all_"+typ+'_'+network+'_r{}.csv'.format(recurrencia), index=False)
combined_output_rpm.to_csv( root_path+"output_all_"+typ+'_rpm_'+network+'_r{}.csv'.format(recurrencia), index=False)
combined_output_pow.to_csv( root_path+"output_all_"+typ+'_pow_'+network+'_r{}.csv'.format(recurrencia), index=False)
combined_output_torq.to_csv( root_path+"output_all_"+typ+'_torq_'+network+'_r{}.csv'.format(recurrencia), index=False)